#!/usr/bin/ruby

infile = ARGV.shift

fc = File.read(infile)
bh = '///////////////////////////////////////////////////////////////////////////////'

block_map = {}
curr_block_header = ''
fc.split(/#{bh}\n/m).each { |txt|
  if txt.start_with?('//')
    curr_block_header = txt[3..-1].strip
    next
  end
  txt.scan(/#define ([A-Z]+)_BLOCK_TYPE\S*\s*(0x[x0-9a-f]+)/) { |type, id|
    block_map.store(id.to_i(16), [type, curr_block_header])
  }
}

# Now write the header file
s = "#ifndef BLOCK_TYPES_H
#define BLOCK_TYPES_H

#include <stdint.h>

// This file is automatically generated by block_name_parser.rb. Manual edits will be lost!

const char* get_block_desc(uint32_t block_type)
{
  "
  block_map.each { |k, v|
    s << "\tif (block_type == #{k}) return \"#{v[1]}\";\n"
  }
s << "\t return \"\";
}

#endif
"

puts s
